name: Feature Request
description: Suggest a new feature
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?

  - type: dropdown
    id: uds-service
    attributes:
      label: Related UDS Service (if applicable)
      options:
        - "0x10 - Diagnostic Session Control"
        - "0x11 - ECU Reset"
        - "0x14 - Clear Diagnostic Information"
        - "0x19 - Read DTC Information"
        - "0x22 - Read Data By Identifier"
        - "0x27 - Security Access"
        - "0x34-0x37 - Transfer Services"
        - "ISO-TP Transport"
        - "SLCAN"
        - "Other"
        - "N/A"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots
